def dichotomie(tab, x):
    debut = 0
    fin = ...
    while debut <= ...
        milieu = ...
        if tab[milieu] == x:
            return ...
        elif tab[milieu] < x:
            debut = milieu + 1
        else:
            ...
    return ...